INSERT INTO teachers (user_id, first_name, last_name, subject_specialization) VALUES
(5, 'Aisha', 'Rahman', 'Mathematics'),
(6, 'Omar', 'Siddiqui', 'Science'),
(7, 'Liam', 'Patel', 'English'),
(8, 'Maya', 'Al-Qasimi', 'Arabic'),
(9, 'Sophia', 'Mendes', 'ICT'),
(10, 'Daniel', 'Hughes', 'Physical Education'),
(11, 'Fatima', 'Khan', 'Art'),
(12, 'Noah', 'Fernandez', 'Music'),
(13, 'Zara', 'Hassan', 'Social Studies'),
(14, 'Ethan', 'Varghese', 'Mathematics'),
(15, 'Layla', 'Nasser', 'Science'),
(16, 'Jonas', 'Petrov', 'English'),
(17, 'Sara', 'Mahmoud', 'Arabic'),
(18, 'Yusuf', 'Karim', 'ICT'),
(19, 'Hana', 'Othman', 'Physical Education'),
(20, 'Rami', 'Saleh', 'Art'),
(21, 'Isabella', 'Costa', 'Music'),
(22, 'Khalid', 'Jabari', 'Social Studies'),
(23, 'Emily', 'Turner', 'Mathematics'),
(24, 'Owen', 'Mitchell', 'Science');
