FROM node:18-alpine AS builder

WORKDIR /app
RUN npm install -g pnpm

COPY package.json ./
COPY . .

RUN pnpm install --no-frozen-lockfile
RUN pnpm build

FROM node:18-alpine AS production

WORKDIR /app
RUN npm install -g pnpm

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
